defaults: &defaults
#  host: 127.0.0.1
#  port: 27017
  host: troup.mongohq.com
  port: 10048
  username: zhangkai
  password: abcd.1234
#  host: 10.15.107.212
#  port: 36038
development:
  <<: *defaults
  database: tw_development

test:
  <<: *defaults
  database: tw_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: tw
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
